///////////////////////////////////////////////////////////
//  Attribute.cs
//  Implementation of the Class Attribute
//  Generated by Enterprise Architect
//  Created on:      15-mar-2016 14:08:33
//  Original author: Filipe
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace ThreeDUMLAPI {
	public class Attribute : SoftwareEntity {

		public Attribute(){

		}

		~Attribute(){

		}

	}//end Attribute

}//end namespace ThreeDUMLAPI