///////////////////////////////////////////////////////////
//  ClassAttribute.cs
//  Implementation of the Class ClassAttribute
//  Generated by Enterprise Architect
//  Created on:      28-sep-2016 8:30:00
//  Original author: William Lacerda
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using ThreeDUMLAPI;

namespace ThreeDUMLAPI {
	public class ClassAttribute : IXmlNode
    {

		//public Core.Object m_Object;

		public ClassAttribute(){
            
		}

		~ClassAttribute(){

		}

	}//end Class

}//end namespace ThreeDUMLAPI