///////////////////////////////////////////////////////////
//  ClassDiagram.cs
//  Implementation of the Class ClassDiagram
//  Generated by Enterprise Architect
//  Created on:      15-mar-2016 14:08:33
//  Original author: Filipe
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using ThreeDUMLAPI;
namespace ThreeDUMLAPI {
	public class ClassDiagram : Diagram
    {

        public ClassDiagram(){
            
		}

		~ClassDiagram(){

		}

	}//end ClassDiagram

}//end namespace ThreeDUMLAPI