///////////////////////////////////////////////////////////
//  Generalization.cs
//  Implementation of the Class Generalization
//  Generated by Enterprise Architect
//  Created on:      15-mar-2016 14:08:33
//  Original author: Filipe
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using ThreeDUMLAPI;
namespace ThreeDUMLAPI {
	public class Generalization : Relationship {

		public Generalization(){

		}

		~Generalization(){

		}

	}//end Generalization

}//end namespace ThreeDUMLAPI