///////////////////////////////////////////////////////////
//  LogicalPackage.cs
//  Implementation of the Class LogicalPackage
//  Generated by Enterprise Architect
//  Created on:      15-mar-2016 14:08:33
//  Original author: Filipe
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using ThreeDUMLAPI;
namespace ThreeDUMLAPI {
	public class LogicalPackage : LogicalEntity {

		public LogicalPackage(){

		}

		~LogicalPackage(){

		}

	}//end LogicalPackage

}//end namespace ThreeDUMLAPI