///////////////////////////////////////////////////////////
//  Operation.cs
//  Implementation of the Class Operation
//  Generated by Enterprise Architect
//  Created on:      28-sep-2016 8:30:00
//  Original author: William Lacerda
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;

using ThreeDUMLAPI;

//Class used to save operations from classes
namespace ThreeDUMLAPI {
	public class Operation : IXmlNode {

		public Operation(){

		}

		~Operation(){

		}

	}//end Operation

}//end namespace ThreeDUMLAPI