///////////////////////////////////////////////////////////
//  Attribute.cs
//  Implementation of the Class Attribute
//  Generated by Enterprise Architect
//  Created on:      15-mar-2016 14:08:33
//  Original author: Filipe
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;

using ThreeDUMLAPI;

//Class used to save operations from classes
namespace ThreeDUMLAPI {
	public class Operation : IXmlNode {

		public Operation(){

		}

		~Operation(){

		}

	}//end Operation

}//end namespace ThreeDUMLAPI