///////////////////////////////////////////////////////////
//  Attribute.cs
//  Implementation of the Class Attribute
//  Generated by Enterprise Architect
//  Created on:      15-mar-2016 14:08:33
//  Original author: Filipe
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;

using ThreeDUMLAPI;

//Class used to save Parameters from classes' operations
namespace ThreeDUMLAPI {
	public class Parameter : IXmlNode {

		public Parameter(){

		}

		~Parameter(){

		}

	}//end Operation

}//end namespace ThreeDUMLAPI