///////////////////////////////////////////////////////////
//  Parameter.cs
//  Implementation of the Class Parameter
//  Generated by Enterprise Architect
//  Created on:      28-sep-2016 8:30:00
//  Original author: William Lacerda
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;

using ThreeDUMLAPI;

//Class used to save Parameters from classes' operations
namespace ThreeDUMLAPI {
	public class Parameter : IXmlNode {

		public Parameter(){

		}

		~Parameter(){

		}

	}//end Operation

}//end namespace ThreeDUMLAPI