///////////////////////////////////////////////////////////
//  Relationship.cs
//  Implementation of the Class Relationship
//  Generated by Enterprise Architect
//  Created on:      15-mar-2016 14:08:33
//  Original author: Filipe
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using ThreeDUMLAPI;
namespace ThreeDUMLAPI {
	public class Relationship : IXmlNode {

		public ThreeDUMLAPI.SoftwareEntity m_SoftwareEntity;

		public Relationship(){

		}

		~Relationship(){

		}

	}//end Relationship

}//end namespace ThreeDUMLAPI