///////////////////////////////////////////////////////////
//  SoftwareEntity.cs
//  Implementation of the Class SoftwareEntity
//  Generated by Enterprise Architect
//  Created on:      15-mar-2016 08:28:14
//  Original author: Filipe
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using ThreeDUMLAPI;
namespace ThreeDUMLAPI {
	public abstract class SoftwareEntity : IXmlNode {

        //public Core.Method m_Method;
        //public Core.Attribute m_Attribute;
        public Dictionary<IXmlNode, IXmlNode> Relationships { get; private set; }
        public List<IXmlNode> Methods { get; private set; }

        public SoftwareEntity(){
            Relationships = new Dictionary<IXmlNode, IXmlNode>();
            Methods = new List<IXmlNode>();

        }
                
        public void AddRelationshipWith(IXmlNode relationship , IXmlNode softwareentity)
        {
            Relationships.Add(relationship, softwareentity);
        }

        public void AddMethod(IXmlNode method)
        {
            Methods.Add(method);
        }

        ~SoftwareEntity(){

		}

	}//end SoftwareEntity

}//end namespace ThreeDUMLAPI