///////////////////////////////////////////////////////////
//  Association.cs
//  Implementation of the Class Association
//  Generated by Enterprise Architect
//  Created on:      15-mar-2016 14:08:32
//  Original author: Filipe
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using ThreeDUMLAPI;
namespace ThreeDUMLAPI {
	public class Association : Relationship {

		public Association(){

		}

		~Association(){

		}

	}//end Association

}//end namespace ThreeDUMLAPI