///////////////////////////////////////////////////////////
//  Class.cs
//  Implementation of the Class Class
//  Generated by Enterprise Architect
//  Created on:      15-mar-2016 14:08:33
//  Original author: Filipe
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using ThreeDUMLAPI;
namespace ThreeDUMLAPI {
	public class Class : SoftwareEntity {

		//public Core.Object m_Object;

		public Class(){
            
		}

		~Class(){

		}

	}//end Class

}//end namespace ThreeDUMLAPI