///////////////////////////////////////////////////////////
//  Composition.cs
//  Implementation of the Class Composition
//  Generated by Enterprise Architect
//  Created on:      15-mar-2016 15:11:25
//  Original author: Filipe
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using ThreeDUMLAPI;
namespace ThreeDUMLAPI {
	public class Composition : Relationship {

		public Composition(){

		}

		~Composition(){

		}

	}//end Composition

}//end namespace ThreeDUMLAPI