///////////////////////////////////////////////////////////
//  Lifeline.cs
//  Implementation of the Lifeline Lifeline
//  Generated by Enterprise Architect
//  Created on:      15-mar-2016 14:08:33
//  Original author: Filipe
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using ThreeDUMLAPI;
namespace ThreeDUMLAPI
{
    public class Lifeline : SoftwareEntity
    {

        //public Core.Object m_Object;

        public Lifeline()
        {

        }

        //public override IXmlNode FindById(List<IXmlNode> list, string id , IXmlNode r = null)
        //{
        //    //Lifeline r = new Lifeline();
        //    foreach(Lifeline l in list)
        //    {
        //        if(l.Id.Equals(id))
        //        {
        //            r = l;
        //        }
        //    }
        //    return r;
        //}

        ~Lifeline()
        {

        }

    }//end Class

}//end namespace ThreeDUMLAPI