///////////////////////////////////////////////////////////
//  Loop.cs
//  Implementation of the Class Loop
//  Generated by Enterprise Architect
//  Created on:      15-mar-2016 14:08:33
//  Original author: Filipe
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using ThreeDUMLAPI;
namespace ThreeDUMLAPI {
	public class Loop : LogicalEntity {

		public Loop(){

		}

		~Loop(){

		}

	}//end Loop

}//end namespace ThreeDUMLAPI