///////////////////////////////////////////////////////////
//  Method.cs
//  Implementation of the Class Method
//  Generated by Enterprise Architect
//  Created on:      15-mar-2016 14:08:33
//  Original author: Filipe
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace ThreeDUMLAPI {
	public class Method : IXmlNode{

		public Method(){

		}

        //public override IXmlNode FindById(List<IXmlNode> list, string id , IXmlNode r = null)
        //{
        //    //Method r = new Method();
        //    foreach (Method m in list)
        //    {
        //        if (m.Id.Equals(id))
        //        {
        //            r = m;
        //        }
        //    }
        //    return r;
        //}

        ~Method(){

		}

	}//end Method

}//end namespace ThreeDUMLAPI