///////////////////////////////////////////////////////////
//  Package.cs
//  Implementation of the Class Package
//  Generated by Enterprise Architect
//  Created on:      15-mar-2016 14:08:33
//  Original author: Filipe
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using ThreeDUMLAPI;
namespace ThreeDUMLAPI {
	public class Package : IXmlNode {

        //public Core.Diagram m_Diagram;
        public List<IXmlNode> ClassDiagrams { get; set; }
        public List<IXmlNode> SequenceDiagrams { get; set; }

		public Package(){
            ClassDiagrams = new List<IXmlNode>();
            SequenceDiagrams = new List<IXmlNode>();
		}

		~Package(){

		}

	}//end Package

}//end namespace ThreeDUMLAPI